services:
  acme-grafana:
    image: grafana/grafana:9.5.1
    ports:
      - 3000:3000
    user: "1000:1000"
    environment:
      GF_SERVER_PROTOCOL: "https"
      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_DOMAIN: "ops.acme.test"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_CERT_FILE: "/etc/grafana/cert.pem"
      GF_SERVER_CERT_KEY: "/etc/grafana/key.pem"
      GF_SECURITY_ADMIN_USER: "devops_fallback"
      GF_SECURITY_ADMIN_PASSWORD: "test"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "acme-ops"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "acme-ops-grafana"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "acme-ops-grafana-secret"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://id.acme.test:8443/auth/realms/acme-ops/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://id.acme.test:8443/auth/realms/acme-ops/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://id.acme.test:8443/auth/realms/acme-ops/protocol/openid-connect/userinfo"
      # Generic client role mapping does not work because of '-' in the client name
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "resource_access.grafana.roles[0]"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: "true"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "mailhog"
      GF_SMTP_PORT: 1025
    volumes:
#      - ./run/grafana:/var/lib/grafana:z
#      - ../../../config/stage/dev/grafana/provisioning:/etc/grafana/provisioning:z
      - ../../../config/stage/dev/grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:z
      - ../../../config/stage/dev/grafana/provisioning/dashboards/keycloak-metrics_rev1.json:/etc/grafana/provisioning/dashboards/keycloak-metrics_rev1.json:z
      - ../../../config/stage/dev/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:z
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/grafana/cert.pem:z
      - ../../../config/stage/dev/tls/acme.test+1-key.pem:/etc/grafana/key.pem:z
      - ${CA_ROOT_CERT:-}:/etc/ssl/certs/ca-cert-acme-root.crt:z
    extra_hosts:
      # ${DOCKER_HOST_IP:-172.17.0.1} is host.docker.internal
      - "id.acme.test:${DOCKER_HOST_IP:-172.17.0.1}"